### ISSUE TITLE
[버그] 모바일 UI Modal 포지션 관련

### ISSUE THREAD

**Issue by sh9351** [MEGAWRITING/megawriting-issue#4]
**Describe the bug**
모바일 UI의 모달이 하단으로 이동하여 버튼이 가려짐.

**To Reproduce**
1. 모바일에서 아티클 편집 화면(/article/editor/:id) / 보안토큰 발급 페이지 / 기타 모달 접속
2. 제출하기 버튼 클릭

**Screenshots**
![Screenshot](https://github.com/MEGAWRITING/megawriting-issue/assets/70079686/e2f5dce0-f8be-4b1d-a4ed-b7f9255403e9)

**Environment**
 - OS: Android 13
 - Browser: Chrome 121.0.6167.178
 - Kernal version: 4.14.186-27218697 

**Additional context**
보안토큰 발급 등 모달의 경우 `container.current.contains(e.target)` `/components/Modal/Modal.js:24` (추정)에 의해 닫을 수 있지만, 저장하기 모달의 경우 모달 외부를 클릭하면 emphasis가 설정될 뿐 실제 모달이 닫히지는 않기에, 작성한 아티클 내용 전체를 잃을 수도 있습니다.  
DevTools의 에뮬레이터를 이용하여 확인한 결과 발생하지 않았습니다. 이는 해당 버그가 Desktop과 Mobile 간의 환경 차이 때문에 발생한다는 의미를 지닙니다.  
이상입니다.

**Comment by mjun0328** [comment]
안녕하세요, 먼저 MEGAWRITING에 관심 가져주셔서 감사합니다 :)

모바일 환경에서 바텀시트의 버튼 부분이 가려지는 문제를 확인하였습니다.
모바일 브라우저의 경우 주소창과 같은 브라우저 자체 컴포넌트로 인해 화면 일부가 가려지는 문제가 종종 발생하기도 합니다. MEGAWRITING에서도 이 부분을 인지하고 있는 상태라 유사 사례들을 찾아보고 분석하는 중에 있습니다.

모바일 브라우저의 환경 특성을 감안한 해결 방법을 모색하는 한편, 그 전까지는 임시 조치 차원에서 화면 가운데 나타나는 모달 형식으로 전환하도록 하겠습니다.

불편을 드려 죄송하고, 이슈를 제보해주셔서 감사드립니다 🙇

**Comment by mjun0328** [comment]
안녕하세요, 현재 WEB [v1.2.2](https://github.com/MEGAWRITING/megawriting-issue/wiki/Release-Notes(WEB)#122)에서 제보해주신 이슈를 해결하였습니다.

추가로 MEGAWRITING 이용에 문제가 있다면 언제든지 문의해주시기 바랍니다. 앞으로도 MEGAWRITING에 많은 관심 부탁드립니다. 🙇

**Comment by sh9351** [comment]
밤 늦게까지 수고 많으십니다! 버그의 원인이 무었이였는지 궁금하네요 ㅎㅎ
좋은 밤 보내세요! :)
