### ISSUE TITLE
[버그] 404 페이지 Canvas resizeHandler 관련

### ISSUE THREAD

**Issue by sh9351** [MEGAWRITING/megawriting-issue#5]
**Describe the bug**
404 Error 페이지의 animate 함수(`/routes/Error/Error.js:136`)가 Canvas를 충분히 clear하지 않아 resize 시 ball, hole, flat 등이 중복으로 그려집니다.

**To Reproduce**
1. MEGAWRITING의 404 페이지를 방문합니다.
2. Ctrl + Wheel을 이용해 확대/축소를 조정합니다.
3. Ball, hole, flat 등이 중복으로 Canvas에 그려집니다.

**Screenshots**
https://github.com/MEGAWRITING/megawriting-issue/assets/70079686/b34dbce8-3ef9-4fde-94f9-d97c6ff66090

**Environment**
 - Browser: Chrome 121.0.6167.189
 - OS: Windows 11 Home 10.0.22621.3155, Windows Feature Experience Pack 1000.22684.1000.0, NT Kernel 6.3

**Additional context**
1. 소스 코드를 분석한 결과 `ctx.clearRect`의 인자로 넘겨주는 `canvas.width`, `canvas.height` 값이 실제 표시되는 canvas의 width, height와 상이하여 발생하는 문제로 추측할 수 있겠습니다만, 실제로 해당 사항이 맞는지는 확인하지 못한 점 양해 부탁드립니다.
2. 만약 위 전제가 사실일 경우, `canvas.width`, `canvas.height`, `window.screen.availWidth`, `window.screen.availHeight` 등의 값 모두 확대/축소를 반영하지 않기에, `canvas.getBoundingClientRect()` 등의 값을 이용하여 `ctx.clearRect` 함수를 호출해야 할 것으로 보입니다.
3. 만약 위 전제가 사실이 아닐 경우, Chrome 에서의 (하드웨어 가속과 관련 있을 수 있는) 오류일 수 있습니다. 이 경우 마땅한 해결책을 찾기 어렵습니다.

**Comment by mjun0328** [comment]
안녕하세요, 먼저 MEGAWRITING에 관심 가져주셔서 감사합니다 :)

404 페이지에서 제보해주신 바와 같이 확대/축소 시 애니메이션이 중첩되어 나타나는 오류를 확인하였습니다.
이슈를 분석한 결과, 화면 크기 변경 등의 이유로 canvas를 초기화할 때 DPR(Device Pixel Ratio)을 고려하지 못한 것이 원인으로 보입니다.

제보해주신 이슈는 다음 릴리즈 버전을 통해 해결될 예정입니다.

이슈를 제보해주셔서 감사드립니다 🙇

**Comment by mjun0328** [comment]
안녕하세요, 현재 WEB [v1.2.1](https://github.com/MEGAWRITING/megawriting-issue/wiki/Release-Notes(WEB)#121)에서 제보해주신 이슈를 해결하였습니다.

추가로 MEGAWRITING 이용에 문제가 있다면 언제든지 문의해주시기 바랍니다. 앞으로도 MEGAWRITING에 많은 관심 부탁드립니다. 🙇

**Comment by sh9351** [comment]
해당 이슈가 재발하지 않는다는 점 확인하였습니다! ✅ 
근데 JS Map은 왜 없애셨나요.. ㅠㅠ
![MG_Datamining](https://github.com/MEGAWRITING/megawriting-issue/assets/70079686/1d29e0db-d7ee-4a61-8725-dd8707213cdb)
항상 감사드립니다! 남은 주말 행복하게 보내시길 바라겠습니다 :smile:
