### ISSUE TITLE
[보안] 아티클 checksum 무결성 검증 관련

### ISSUE THREAD

**Issue by sh9351** [MEGAWRITING/megawriting-issue#6]
API v2의 릴리스와 함께 checksum 항목이 추가된 것을 확인하였습니다.
아직은 checksum 일치 여부가 저장 로직에 강제되지는 않지만,
아래 코드를 이용해 FE와 동일한 checksum을 생성할 수 있습니다.

물론 MEGAWRITING의 학생 사용자 중에서
아래 코드를 읽고 이해할 수 있는 사람이 몇 명이나 될지 의문이 들기는 하지만,
해당 이슈는 단순히 checksum의 무결성이 보장되지 않는다는 점을 의미하며,
이 이슈 이후로 checksum 관련해서는 게시하지 않겠습니다.
이 정도면 개발자님께서도 현실적으로 가능한 최고의 보안을 적용하셨다고 생각이 듭니다.

어차피 새로운 릴리스를 출시하여도 FE가 있는 한 checksum은 언젠가는 위변조 될 수 밖에 없기에,
개발자님께서 굳이 추가로 보안을 강화할 필요가 있으신지는 의문입니다.
항상 수고가 많으십니다. 늦은 밤 안녕히 주무세요.

```js
const ARTICLE_ID = ``
const COOKIE = `connect.sid=`
const TITLE = `Checksum Generator v1`
const CONTENTS = `honestly quite good verification, but na-ah, FE is NOT secure`

const axios = require('axios')
const crypto = require('crypto')

const cipher = ''
    .concat(TITLE, '/')
    .concat(CONTENTS, '/')
    .concat(CONTENTS.substring(0, 300), '4zi8P1$fiPfb/')
    .concat(CONTENTS.length, '+')
    .concat(TITLE.length)
const hash = crypto.createHash('sha1').update(cipher).digest('hex')
console.log(hash)

axios.put(`https://api.megawriting.net/v2/article/${ARTICLE_ID}`, {
    title: TITLE,
    contents: CONTENTS,
    checksum: hash,
    isSubmit: false,
    memo: 'never trust the FE, or else, you might end up leakin\' *quite an amount* of personal information'
}, {
    headers: {
        Cookie: COOKIE
    }
}).then(({ data }) => {
    console.log(data)
})
```

**Comment by mjun0328** [comment]
안녕하세요, 먼저 MEGAWRITING에 관심 가져주셔서 감사합니다 :)

MEGAWRITING은 학생들의 효율적인 학습 역량 향상을 위하여 아티클 작성 시 복사/붙여넣기를 제한하고 있으며, 프론트엔드와 백엔드 차원에서 이러한 부정학습 행위를 차단하기 위하여 노력하고 있습니다.

그러나 문의하신 바와 같이 프론트엔드는 그 특성 상 부정학습 방지 장치의 우회가 얼마든지 가능하고, MEGAWRITING도 이 점을 충분히 인지하고 있습니다. 이번 아티클 저장 시의 checksum(이하 '체크섬') 항목은 1.2.3 버전의 복사/붙여넣기 방지 기능 강화 업데이트의 일환으로 추가된 것입니다만, 이는 서비스 향상과 분석을 위해 실험적으로 도입한 것이며 이러한 이유로 API에서 체크섬을 강제하고 있지는 않습니다.

다시 한번 MEGAWRITING에 관심 가져주시고 문의해주셔서 감사드리며, 문의해주신 소중한 의견을 토대로 MEGAWRITING은 앞으로도 학생들의 학습 역량 향상을 위하여 여러 방면에서 부정학습 행위의 차단에 힘쓰겠습니다.

추가적으로 궁금하신 점이 있으시다면 언제든 편하게 문의하여 주시기 바라며, 문의 사항이 해결되셨다면 본 이슈를 닫아주시면 감사하겠습니다. 🙇
