### ISSUE TITLE
[버그] Modal View 시간 업데이트 지연

### ISSUE THREAD

**Issue by sh9351** [MEGAWRITING/megawriting-issue#8]
**Describe the bug**
아티글 View 페이지의 아티클 작성 시간이 정상적으로 업데이트 되지 않습니다. 최초 로드 후 업데이트 되지 않으며, 컴포넌트 변경 시 갑작스럽게 변경됩니다.

**To Reproduce**
1. 아티클 View 페이지 접속
2. 시간이 변화할 만큼 대기
3. 아무 버튼(+, -, 전송, etc...) 클릭
4. 작성 시간이 갑작스럽게 변경되며, 상기한 버그 발생

**Screenshots**
https://github.com/MEGAWRITING/megawriting-issue/assets/70079686/0eeadbbe-5d2e-4502-8118-72ec0b7145e3
컴포넌트 변경 시 시간이 "Updated just now"에서 "Updated 4 minutes ago"로 변경된 것을 확인할 수 있습니다.

**Environment**
 - Browser: Chrome 125.0.6422.113
 - OS: Windows 11 Home 10.0.22621.3593, Windows Feature Experience Pack 1000.22700.1003.0, NT Kernel 6.3

**Additional context**
`/routes/article/View/View.js:805`(추정) 내 코드를 확인하시면 아래와 같이 timeGap 함숫값을 state 등에 저장하는 것이 아닌 곧바로 UI에 바인딩하고 있다는 점을 확인하실 수 있습니다.
```js
// 아래 코드는 MEGAWRITING FE 신버전에서는 .map 파일을 제공하지 않는 관계로, 저장되어 있던 구버전의 코드입니다.
return (
  <div className={styles.update}>
    <div>
      <span
        onMouseEnter={() => setIsHover1(true)}
        onMouseLeave={() => setIsHover1(false)}
      >
        {`Updated ${timeGap(new Date(saveAt))}`}
      </span>
      <div
        onMouseEnter={() => setIsHover2(true)}
        onMouseLeave={() => setIsHover2(false)}
        show={(isHover1 || isHover2).toString()}
      >
        {time}
      </div>
    </div>
  </div>
);
```
이에 아티클 작성 시간이 실시간으로 업데이트 되지 않고 컴포넌트가 변경될 때에만 timeGap 함수가 실행되어 시간이 업데이트 되는 것으로 보입니다. 해당 버그는 timeGap 함숫값을 state에 저장한 후, setInterval 등으로 시간을 실시간으로 업데이트하여 해결할 수 있습니다. 다만 컴포넌트가 unmount 시 해당 interval을 초기화하지 않으면 성능 문제가 발생할 수 있습니다.

**Comment by sh9351** [comment]
`bug` 레이블을 부여하려고 하였지만 권한이 부족하네요! 혹여나 설정에서 권한을 변경해 주신다면 추후 오픈하는 이슈에는 레이블을 부여하도록 하겠습니다 :)

**Comment by mjun0328** [comment]
안녕하세요, 먼저 MEGAWRITING에 관심 가져주셔서 감사합니다 :)

제보해주신 바와 같이 아티클 열람 페이지에서 최근 업데이트 시각이 시간이 흐름에 따라 자연스럽게 변경되지 않는 오류를 확인하였습니다.
이슈를 분석한 결과, 시간 흐름에 따른 렌더링이 자동으로 이뤄지지 않아 발생한 것이 그 원인으로 보입니다.

제보해주신 이슈는 추후 릴리즈 버전을 통해 해결될 예정입니다.

레이블 권한에 관하여 문의해 주셨습니다만, 죄송스럽게도 레이블의 일관성 유지와 남용 방지 및 내부 업무 규정에 따라 권한을 부여하는 것은 어려울 것 같습니다.
언제나 MEGAWRITING에 관심을 가져주셔서 감사드리며, 이슈를 제보해주셔서 감사드립니다 🙇

**Comment by mjun0328** [comment]
안녕하세요, 현재 WEB [v1.4.0](https://github.com/MEGAWRITING/megawriting-issue/wiki/Release-Notes(WEB)#140)에서 제보해주신 이슈를 해결하였습니다.

추가로 MEGAWRITING 이용에 문제가 있다면 언제든지 문의해주시기 바랍니다. 앞으로도 MEGAWRITING에 많은 관심 부탁드립니다. 🙇
