### ISSUE TITLE
[제안] 회원가입 시 데모 모드 기능 추가

### ISSUE THREAD

**Issue by sh9351** [MEGAWRITING/megawriting-issue#9]
**Describe your request**
MEGAWRITING 신규 회원가입 시의 과정을 볼 기회가 있었습니다. 회원가입 완료 후, 선생님들께서 MEGAWRITING의 기능을 시연하기 위해 직접 학생의 계정으로 로그인하여 서비스 약관 등에 임의로 동의하고 비밀번호를 "12345678"로 설정한 후, 아티클 작성 등의 기능을 신규 학생을 위해 시연하였습니다. 이로 인해 학생들이 오히려 약관을 확인할 수 없게 됩니다. 이에, 선생님들께서 신규 학생을 위해 MEGAWRITING에 회원가입할 때, 약관 동의 등 없이 MEGAWRITING의 기능을 시연할 수 있는 "데모 모드"를 제안드리고자 합니다. 

**Additional context**
신규 회원가입 시 선생님들은 "데모 모드"를 통해 `/welcome` 페이지의 약관 동의 등을 건너뛰고 MEGAWRITING의 아티클 작성 기능 등을 시연할 수 있습니다. 이후 학생들이 집에서 MEGAWRITING에 로그인 하면 약관 동의 화면이 표시되고, 추가적으로 아티클 작성 기능 등을 직접 따라해보며 MEGAWRITING의 시스템을 익힐 수 있는 기능을 제안드립니다. "데모 모드"는 선생님의 계정에서 단순히 UI만 표시할 수 있고, 혹은 Impersonation 버튼을 통해 학생의 계정으로 추가적인 인증 과정 없이 바로 로그인하여 아티클 작성 기능을 시연할 수도 있습니다.

**Comment by mjun0328** [comment]
안녕하세요, 언제나 MEGAWRITING에 관심 가져주셔서 감사합니다 :)

선생님들께서 MEGAWRITING을 시연하는 과정에서 △직접 학생 계정으로 로그인할 수 있다는 점과 △이를 통해 이용약관 등의 동의 절차를 계정 주인인 학생이 아닌 선생님이 대신 할 수 있다는 점을 지적해 주신 것으로 이해됩니다.

답변에 앞서 MEGAWRITING은 회원의 첫 로그인 시 이용약관과 개인정보 처리방침(이하 '이용약관 등')에 관한 동의를 받고 있으며, 이용약관 등은 로그인 여부와 무관하게 홈페이지에 공개되어 상시 열람하실 수 있음을 알려드립니다. 아울러, 회원과 MEGAWRITING 간의 법적 구속력을 갖는 이용약관 등의 동의 절차는 계정 주인인 학생이 직접 이행하여야 하며, 선생님이 시연 등을 이유로 대신 동의하실 수 없습니다. 다만, 해당 학생에게 명시적으로 동의를 얻어 대신 동의하는 것은 권장하지는 않으나 허용되는 방법입니다.

제안해주신 일명 "데모 모드"는 선생님께서 별도의 이용약관 등의 동의 과정 없이 학생 계정으로 활동할 수 있게 함으로써 시연과 같은 작업을 수행할 수 있도록 하는 기능으로 이해됩니다. 이 기능의 구현을 통해 선생님은 학생들에게 MEGAWRITING의 기능을 시연할 수 있는 한편, 학생은 이용약관 등의 동의 절차를 직접 밟을 수 있다는 이점이 있을 것으로 보입니다.

다만, 데모 모드의 도입에 앞서 동의 절차 또한 시연의 대상인지의 여부 등 센터의 요구 사항을 수렴할 필요가 있고, 회원의 사용자 경험적인 요소에 대한 고찰이 선행될 필요가 있어 보입니다. 제안해주신 소중안 의견을 바탕으로 센터 및 회원분들과 소통해보며 최적의 결과가 도출될 수 있도록 노력하겠습니다.

추가적으로 궁금하신 점이나 제안하실 점이 있으시다면 언제든 편하게 문의하여 주시기 바랍니다.
언제나 MEGAWRITING에 관심을 가져주셔서 감사드리며, 소중안 제안에 감사드립니다 🙇

**Comment by sh9351** [comment]
안녕하세요, 주말까지 노고에 감사드립니다.
일전에 제안드린 "데모 모드" 기능에 대하여 센터 의견 수렴 등의 고찰이 선행되어야 한다고 말씀해 주셨습니다.
제안드린 기능에 대한 검토 과정이 어떤 결과를 도출하였는지, 그리고 해당 기능이 실제로 적용되었는지 질문드리고자 합니다.
다시 한번 노고에 감사드리며, 남은 주말 행복히 보내시길 바랍니다.
감사합니다.

**Comment by mjun0328** [comment]
안녕하세요, 답장이 늦어 죄송합니다.

제안해주신 "데모 모드" 기능은 충분히 긍정적인 의견으로 검토되었습니다. 다만, 계획되어 있는 기능 개발이 많아 우선순위에서 다소 밀려있는 상황입니다. 확답드리기는 어려우나 앞선 우선순위의 개발이 마무리되고 비로소 데모 모드의 개발 순서가 왔을 때 재검토에서 개발 의견으로 통과되면 개발이 착수되지 않을까 예상합니다.

언제나 MEGAWRITING에 관심을 가져주셔서 감사드립니다.
